# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest03():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test03(self):
    self.driver.get("https://sms-admin.qiniu.io/users?page=1&size=50")
    self.driver.set_window_size(960, 540)
    self.driver.find_element(By.XPATH, "//input[@value=\'\']").click()
    self.driver.implicitly_wait(10)
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input").send_keys("1382862176")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-input").send_keys(Keys.ENTER)
    self.driver.close()
  
